[book]
title = "mysystem's development book"
authors = ["XXXX Dev Team <hogehoge@example.com>"]
language = "jp"
multilingual = true
src = "src"

[build]
build-dir = "book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["src/assets/mermaid.min.js", "src/assets/mermaid-init.js"]

