version: "3.7"

services:
  mdbook:
    container_name: mdbook
    image: peaceiris/mdbook:v0.4.34-rust      # Minimum image
    # image: peaceiris/mdbook:v0.4.34-rust     # `mdbook test` subcommand is available
    # image: ghcr.io/peaceiris/mdbook:v0.x.x  # Docker images on GitHub Packages
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'

  db:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      TZ: Asia/Tokyo
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
